version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            python3 manage.py test

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only: main
